server:
  port: 8081
spring:
  datasource:
    name: productCatalog_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/productCatalog_db
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgres

springdoc:
  packagesToScan: com.giventake.productcatalog

